-- Marques AutoDetail - Supabase PostgreSQL schema
-- Execute este arquivo no SQL Editor do Supabase antes de iniciar a API.

create table if not exists usuarios (
    id bigint generated by default as identity primary key,
    nome varchar(255) not null,
    email varchar(255) not null,
    senha varchar(255) not null,
    role varchar(255) not null,
    telefone varchar(255),
    ativo boolean default true,
    criado_em timestamp(6) without time zone default now(),
    constraint uk_usuarios_email unique (email),
    constraint ck_usuarios_role check (role in ('CLIENTE', 'EMPRESA', 'ADMIN'))
);

create table if not exists enderecos (
    id bigint generated by default as identity primary key,
    cep varchar(255),
    rua varchar(255),
    numero varchar(255),
    bairro varchar(255),
    cidade varchar(255),
    estado varchar(255)
);

create table if not exists empresas (
    id bigint generated by default as identity primary key,
    nome_fantasia varchar(255) not null,
    descricao varchar(1000),
    telefone varchar(255),
    cnpj varchar(255),
    foto_url varchar(255),
    latitude double precision,
    longitude double precision,
    media_avaliacao double precision default 0,
    aberta boolean default true,
    usuario_id bigint not null,
    endereco_id bigint not null,
    constraint fk_empresas_usuario foreign key (usuario_id) references usuarios(id) on delete cascade,
    constraint fk_empresas_endereco foreign key (endereco_id) references enderecos(id) on delete restrict,
    constraint uk_empresas_usuario unique (usuario_id),
    constraint uk_empresas_endereco unique (endereco_id)
);

create table if not exists servicos (
    id bigint generated by default as identity primary key,
    nome varchar(255) not null,
    descricao varchar(1000),
    preco numeric(38, 2) not null,
    duracao_minutos integer not null,
    ativo boolean not null default true,
    empresa_id bigint not null,
    constraint fk_servicos_empresa foreign key (empresa_id) references empresas(id) on delete cascade,
    constraint ck_servicos_preco check (preco >= 0),
    constraint ck_servicos_duracao check (duracao_minutos is null or duracao_minutos > 0)
);

create table if not exists agendamentos (
    id bigint generated by default as identity primary key,
    data date not null,
    hora time(6) without time zone not null,
    status varchar(255) not null default 'PENDENTE',
    observacao varchar(1000),
    cliente_id bigint not null,
    empresa_id bigint not null,
    servico_id bigint not null,
    criado_em timestamp(6) without time zone not null default now(),
    constraint fk_agendamentos_cliente foreign key (cliente_id) references usuarios(id) on delete cascade,
    constraint fk_agendamentos_empresa foreign key (empresa_id) references empresas(id) on delete cascade,
    constraint fk_agendamentos_servico foreign key (servico_id) references servicos(id) on delete restrict,
    constraint ck_agendamentos_status check (status in ('PENDENTE', 'CONFIRMADO', 'RECUSADO', 'CANCELADO', 'CONCLUIDO'))
);

create table if not exists favoritos (
    id bigint generated by default as identity primary key,
    cliente_id bigint not null,
    empresa_id bigint not null,
    constraint fk_favoritos_cliente foreign key (cliente_id) references usuarios(id) on delete cascade,
    constraint fk_favoritos_empresa foreign key (empresa_id) references empresas(id) on delete cascade,
    constraint uk_favoritos_cliente_empresa unique (cliente_id, empresa_id)
);

create table if not exists avaliacoes (
    id bigint generated by default as identity primary key,
    nota integer not null,
    comentario varchar(1000),
    criado_em timestamp(6) without time zone not null default now(),
    cliente_id bigint not null,
    empresa_id bigint not null,
    agendamento_id bigint not null,
    constraint fk_avaliacoes_cliente foreign key (cliente_id) references usuarios(id) on delete cascade,
    constraint fk_avaliacoes_empresa foreign key (empresa_id) references empresas(id) on delete cascade,
    constraint fk_avaliacoes_agendamento foreign key (agendamento_id) references agendamentos(id) on delete cascade,
    constraint uk_avaliacoes_agendamento unique (agendamento_id),
    constraint ck_avaliacoes_nota check (nota between 1 and 5)
);

create table if not exists horarios_disponiveis (
    id bigint generated by default as identity primary key,
    dia_semana varchar(255) not null,
    hora_inicio time(6) without time zone not null,
    hora_fim time(6) without time zone not null,
    ativo boolean not null default true,
    empresa_id bigint not null,
    constraint fk_horarios_empresa foreign key (empresa_id) references empresas(id) on delete cascade,
    constraint ck_horarios_dia check (dia_semana in ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')),
    constraint ck_horarios_intervalo check (hora_inicio is null or hora_fim is null or hora_inicio < hora_fim)
);

create index if not exists idx_empresas_usuario_id on empresas(usuario_id);
create index if not exists idx_empresas_endereco_id on empresas(endereco_id);
create index if not exists idx_servicos_empresa_id on servicos(empresa_id);
create index if not exists idx_servicos_ativo on servicos(ativo);
create index if not exists idx_agendamentos_cliente_id on agendamentos(cliente_id);
create index if not exists idx_agendamentos_empresa_id on agendamentos(empresa_id);
create index if not exists idx_agendamentos_servico_id on agendamentos(servico_id);
create index if not exists idx_agendamentos_data_hora on agendamentos(data, hora);
create index if not exists idx_agendamentos_empresa_data_status
    on agendamentos(empresa_id, data, status);
create index if not exists idx_favoritos_cliente_id on favoritos(cliente_id);
create index if not exists idx_favoritos_empresa_id on favoritos(empresa_id);
create index if not exists idx_avaliacoes_empresa_id on avaliacoes(empresa_id);
create index if not exists idx_avaliacoes_cliente_id on avaliacoes(cliente_id);
create index if not exists idx_horarios_empresa_id on horarios_disponiveis(empresa_id);
create index if not exists idx_horarios_ativo on horarios_disponiveis(ativo);
create index if not exists idx_horarios_empresa_dia_ativo
    on horarios_disponiveis(empresa_id, dia_semana)
    where ativo = true;
create unique index if not exists uk_usuarios_email_lower on usuarios(lower(email));

insert into usuarios (id, nome, email, senha, role, telefone, ativo, criado_em)
values (
    1,
    'Marques AutoDetail',
    'empresa@marques.com',
    '$2a$10$7EqJtq98hPqEX7fNZaFWoOhi7xH4D2PZy6Zl4K0wMe6c5dT3uU3eK',
    'EMPRESA',
    '1199999-9999',
    true,
    now()
)
on conflict (email) do nothing;

insert into enderecos (id, cep, rua, numero, bairro, cidade, estado)
values (1, null, 'Av. Paulista', '1000', 'Bela Vista', 'Sao Paulo', 'SP')
on conflict (id) do nothing;

insert into empresas (
    id, nome_fantasia, descricao, telefone, cnpj, foto_url, latitude, longitude,
    media_avaliacao, aberta, usuario_id, endereco_id
)
values (
    1,
    'Marques AutoDetail',
    'Estetica automotiva premium com lavagem tecnica, polimento e protecao.',
    '1199999-9999',
    null,
    null,
    -23.5632,
    -46.6544,
    4.9,
    true,
    1,
    1
)
on conflict (id) do nothing;

insert into servicos (id, nome, descricao, preco, duracao_minutos, ativo, empresa_id)
values
    (1, 'Lavagem completa', 'Lavagem externa, interna e acabamento dos detalhes.', 80.00, 90, true, 1),
    (2, 'Polimento tecnico', 'Correcao de pintura, brilho e protecao da lataria.', 150.00, 180, true, 1),
    (3, 'Higienizacao interna', 'Limpeza profunda de bancos, carpetes, painel e teto.', 120.00, 150, true, 1),
    (4, 'Vitrificacao', 'Protecao premium da pintura com maior durabilidade.', 450.00, 360, true, 1)
on conflict (id) do nothing;

insert into horarios_disponiveis (id, dia_semana, hora_inicio, hora_fim, ativo, empresa_id)
values
    (1, 'MONDAY', '08:00', '18:00', true, 1),
    (2, 'TUESDAY', '08:00', '18:00', true, 1),
    (3, 'WEDNESDAY', '08:00', '18:00', true, 1),
    (4, 'THURSDAY', '08:00', '18:00', true, 1),
    (5, 'FRIDAY', '08:00', '18:00', true, 1),
    (6, 'SATURDAY', '09:00', '14:00', true, 1)
on conflict (id) do nothing;

select setval(pg_get_serial_sequence('usuarios', 'id'), coalesce((select max(id) from usuarios), 1), true);
select setval(pg_get_serial_sequence('enderecos', 'id'), coalesce((select max(id) from enderecos), 1), true);
select setval(pg_get_serial_sequence('empresas', 'id'), coalesce((select max(id) from empresas), 1), true);
select setval(pg_get_serial_sequence('servicos', 'id'), coalesce((select max(id) from servicos), 1), true);
select setval(pg_get_serial_sequence('agendamentos', 'id'), coalesce((select max(id) from agendamentos), 1), true);
select setval(pg_get_serial_sequence('favoritos', 'id'), coalesce((select max(id) from favoritos), 1), true);
select setval(pg_get_serial_sequence('avaliacoes', 'id'), coalesce((select max(id) from avaliacoes), 1), true);
select setval(pg_get_serial_sequence('horarios_disponiveis', 'id'), coalesce((select max(id) from horarios_disponiveis), 1), true);

alter table usuarios enable row level security;
alter table enderecos enable row level security;
alter table empresas enable row level security;
alter table servicos enable row level security;
alter table agendamentos enable row level security;
alter table favoritos enable row level security;
alter table avaliacoes enable row level security;
alter table horarios_disponiveis enable row level security;

do $$
begin
    if not exists (select 1 from pg_roles where rolname = 'marques_api_user') then
        create role marques_api_user login;
    end if;
end $$;

grant usage on schema public to marques_api_user;
grant select, insert, update, delete on all tables in schema public to marques_api_user;
grant usage, select, update on all sequences in schema public to marques_api_user;

alter default privileges in schema public grant select, insert, update, delete on tables to marques_api_user;
alter default privileges in schema public grant usage, select, update on sequences to marques_api_user;

drop policy if exists backend_all_usuarios on usuarios;
create policy backend_all_usuarios on usuarios for all to marques_api_user using (true) with check (true);

drop policy if exists backend_all_enderecos on enderecos;
create policy backend_all_enderecos on enderecos for all to marques_api_user using (true) with check (true);

drop policy if exists backend_all_empresas on empresas;
create policy backend_all_empresas on empresas for all to marques_api_user using (true) with check (true);

drop policy if exists backend_all_servicos on servicos;
create policy backend_all_servicos on servicos for all to marques_api_user using (true) with check (true);

drop policy if exists backend_all_agendamentos on agendamentos;
create policy backend_all_agendamentos on agendamentos for all to marques_api_user using (true) with check (true);

drop policy if exists backend_all_favoritos on favoritos;
create policy backend_all_favoritos on favoritos for all to marques_api_user using (true) with check (true);

drop policy if exists backend_all_avaliacoes on avaliacoes;
create policy backend_all_avaliacoes on avaliacoes for all to marques_api_user using (true) with check (true);

drop policy if exists backend_all_horarios_disponiveis on horarios_disponiveis;
create policy backend_all_horarios_disponiveis on horarios_disponiveis for all to marques_api_user using (true) with check (true);

-- Defina a senha da role fora do controle de versao, por exemplo:
-- alter role marques_api_user with password 'uma-senha-forte';
